### ISSUE TITLE
Light version of boilerplate

### ISSUE THREAD

**Issue by nicksp** [nicksp/redux-webpack-es6-boilerplate#10]
Without Redux support and related libraries. Would be handy to have in some development cases.

**Comment by Ouadie** [comment]
There is a a lot of **react-boilerplate** without redux out there so I don't think that this enhancement is necessary

**Comment by nicksp** [comment]
@Ouadie Yes indeed. Apart from that i noticed, tha use more and more React+Redux combination in all my projects personally, thus will keep these two in my upcoming update to the boilerplate.
