### ISSUE TITLE
export NODE_ENV is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Hazantip** [nicksp/redux-webpack-es6-boilerplate#21]
_win10 node 6.2.2 npm 3.9.6_
when `npm run build` error is here: 

> export NODE_ENV=production & NODE_ENV=production & webpack -p --config ./config/webpack.config.prod.js --progress

**Comment by Hazantip** [comment]
solved with this:
**[http://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman](url)**

**Comment by nicksp** [comment]
In the [upcoming update](https://github.com/nicksp/redux-webpack-es6-boilerplate/blob/master/README.md) to the boilerplate, i'm using [cross-env lib](https://www.npmjs.com/package/cross-env) which fixes aforementioned problem. Thanks for the heads up.
