### ISSUE TITLE
Build failed?

### ISSUE THREAD

**Issue by katopz** [nicksp/redux-webpack-es6-boilerplate#31]
I'm clone (clean) and build via Windows and getting this build failed

![failed](https://cloud.githubusercontent.com/assets/97060/18299557/05e0ead6-74ec-11e6-999e-4606322bfdd9.png)

Any hint? Thanks.

**Comment by nicksp** [comment]
Hi @katopz 

Could you please run these commands:
1. `npm cache clear`
2. Open Git Bash (which you get when you install Git for Windows), and navigate to boileplate's folder from which you want to remove npm packages, and run: `for package in`ls node_modules`; do npm uninstall $package; done;`

After that try to install project from scratch followind steps from README.md one more time and let me know how it goes?

**P.S.** Try to run all commands in Git Bash please.

**Comment by katopz** [comment]
Hi @nicksp ,

Still no joy and also failed on my Mac 
![screen shot 2016-09-08 at 20 03 39](https://cloud.githubusercontent.com/assets/97060/18350327/9e5c5fe8-75ff-11e6-9aff-81c19bbecee9.png)
P.S. Git Bash on Windows is even worst it display random junk ascii don't ask me why.

**Comment by nicksp** [comment]
@katopz Even on Mac? Hmmm that's weird.
Is it the same error on mac as on Windows?

Tell me which npm version do you use? Will try to check on my machine

**Comment by kjellski** [comment]
Same here:

D:\projects\app-name>npm --version
3.10.3

D:\projects\app-name>node --version
v6.5.0

**Comment by nicksp** [comment]
@katopz @kjellski Guys, tried setup process several times on my machine and all times it worked fine. Would be helpful if someone could investigate the problem locally.

<img width="1433" alt="caae504c8f4d1dbc4062a6f351bca2b8" src="https://cloud.githubusercontent.com/assets/579331/18610782/3418ef8e-7d25-11e6-8726-d66b180a03a0.png">

**Comment by RanjithNair** [comment]
@nicksp @kjellski @katopz  I was also getting issues while trying to run on my windows laptop. I was able to get it working after i made the changes in the way "include" was set in the webpack config file.  I changed that to :-
`include: path.resolve(__dirname, "../src/client")`

**Comment by katopz** [comment]
Hi @nicksp 

It's working now on my Mac, without doing anything. I think something not quite right about sys environment. I have 100 of boilerplates on my Mac at that time and some more atm. 

I'm not sure what causing this but yeah after doing something else and get back to this (git clone and npm i as usual) it's just work. 👻  (didn't trying on Windows yet)

Thanks

**Comment by nicksp** [comment]
Hey @katopz 

I'm glad it works now for you ;) Might be smth. related to sys env as you mentioned, but still quite hard to predict what it is without getting error on local setup.

Will give a try to the solution proposed by @RanjithNair 

BTW @kjellski Can you prove [that change](https://github.com/nicksp/redux-webpack-es6-boilerplate/issues/31#issuecomment-247808354) fixes issues on your machine? Would be nice to hear other's responses

**Comment by edcolcode** [comment]
Hi all,

I followed the instructions described below. When I run npm run build I get this:

ERROR in ./src/client/assets/styles/styles.scss
Module parse failed: D:\Users\Edgar\Desktop\Temp\js\redux-webpack-es6-boilerplate\src\client\assets\styles\styles.scss Unexpected token (1:5)
You may need an appropriate loader to handle this file type.
| body {
|   background: #f1f1f1;
|   padding-top: 30px;
 @ ./src/client/scripts/production.js 5:0-29

ERROR in ./src/client/assets/javascripts/app/index.js
Module parse failed: D:\Users\Edgar\Desktop\Temp\js\redux-webpack-es6-boilerplate\src\client\assets\javascripts\app\index.js Unexpected token (22:2)
You may need an appropriate loader to handle this file type.
| // Render the React application to the DOM
| render(
|   <AppContainer errorReporter={Redbox}>
|     <Root store={store} history={history} />
|   </AppContainer>,
 @ ./src/client/scripts/production.js 8:0-26

**Comment by RanjithNair** [comment]
@edcolcode : I was also getting similar issues? Did you try what i had proposed?

>  I was also getting issues while trying to run on my windows laptop. I was able to get it working after i made the changes in the way "include" was set in the webpack config file. I changed that to :-
> `include: path.resolve(__dirname, "../src/client")`

**Comment by edcolcode** [comment]
Thanks @RanjithNair is working now. I make that change in the tree webpack config files also I imported the path module in webpack.config.development.

Thanks again.

**Comment by nicksp** [comment]
So many response. Thank you all guys. You help me make this boilerplate more stable and less error-prone. ✌️

**Comment by nicksp** [comment]
The fix #33 has been deployed. Thus, closing this issue. Really hope that everyone's failures are gonna be resolved with that change.
