### ISSUE TITLE
Discussion: Tests

### ISSUE THREAD

**Issue by hassankhan** [nicksp/redux-webpack-es6-boilerplate#36]
I see Enzyme's mentioned, which is awesome. Can we keep all tests under `test/`, keeps things simpler?

Also it seems Jest is back in vogue, I haven't used it at all but happy to give it a shot.

**Comment by nicksp** [comment]
Hey @hassankhan 

Being involved in couple of projects recently, i've got a good habit working with `AVA` for all unit tests i wrote nowadays :) It's much much simple than any existing test frameworks and still gives you all features and power needed.And i'm very happy with that. 

for more in-depth stuff give this famous post a read https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4#.kfhyy2vcz, where Eric rambling about tests in general and `Tape` in particular (which is a predecessor of ES2017 compliant and promises ready `AVA` framework). And that's what i'm gonna update this boilerplate with :)

What do you think @hassankhan ?
