### ISSUE TITLE
Webpack 2.1.0-beta.25 support?

### ISSUE THREAD

**Issue by devdlabs** [nicksp/redux-webpack-es6-boilerplate#37]
if upgraded to webpack 2.1.0-beta.25 it fails to run

**Comment by nicksp** [comment]
Hi @devdlabs,

I haven't checked it yet. Probably it introduces some breaking changes or whatever.
Will probably wait until final version is arrived.

**Comment by nicksp** [comment]
Will close that issue for the time being.
