### ISSUE TITLE
Support for PostCSS

### ISSUE THREAD

**Issue by oyeanuj** [nicksp/redux-webpack-es6-boilerplate#41]
Hi @nicksp,

I was wondering if the boilerplate supports or intends to support either PostCSS or styled-components instead of plain SASS? Or is there a recipe or a guide to switch one out for the other?

Thank you for putting out this boilerplate!

**Comment by nicksp** [comment]
Hello @oyeanuj 

I was kinda busy with my last project, so haven't had a chance to work more on this project, which is unfortunate. BUT...i am ready to give it a more boost soon, and yes, PostCSS and CSS Modules are in my TODO list ;) So stay tuned ;-)

And if you're willing to commit to the project, pull requests are very welcome! Just drop me a line to discuss the topic beforehand.

**Comment by alisonailea** [comment]
I'm happy to help with this! I've been trying to add css modules for the last half hour but they are failing silently. Any idea what could be breaking them?
