### ISSUE TITLE
PR: Add support for `eslint-plugin-compat`

### ISSUE THREAD

**Issue by amilajack** [nicksp/redux-webpack-es6-boilerplate#43]
[This eslint plugin](http://github.com/amilajack/eslint-plugin-compat) lints against APIs that are only supported by target browsers 🎉 Would a PR for this be welcome?

**Here's a demo of it in action**

![demo of plugin usage](https://raw.githubusercontent.com/amilajack/eslint-plugin-compat/master/eslint-plugin-compat-demo.gif)

**Comment by nicksp** [comment]
Hey @amilajack 

Sorry for the delay in response. Been busy with projects....
Yeah it looks really nice and i'd like to have it as PR for my boilerplate, which i'm going to significantly update in several next days...

**Comment by nicksp** [comment]
@amilajack Do you think you'll have a chance to submit PR?

**Comment by amilajack** [comment]
Sure thing!

**Comment by amilajack** [comment]
Having trouble doing this because i'm not used to the kinds of configuration setup this project uses. I also cant seem to run the test correctly because they keep failing

**Comment by nicksp** [comment]
@amilajack You can skip tests for now, as i said in README they fail and am rewriting them atm to the setup i'm more used to. If you need help with anything else, just let me know.
