### ISSUE TITLE
no need to use lodash/assign while Object.assign() is available

### ISSUE THREAD

**Issue by liesislukas** [nicksp/redux-webpack-es6-boilerplate#44]
Any benefits to use lodash and have extra dependency while function is already available at no extra cost?

https://github.com/nicksp/redux-webpack-es6-boilerplate/blob/master/src/client/assets/javascripts/features/friends/friends.js#L94

**Comment by nicksp** [comment]
haha, no need actually. Will change accordingly. 
Thanks for pointing this out :-)
