### ISSUE TITLE
PR: ReactRouter v4

### ISSUE THREAD

**Issue by Lutando** [nicksp/redux-webpack-es6-boilerplate#45]
Would a PR with an update for ReactRouter v4 be welcomed?

**Comment by nicksp** [comment]
Hi @Lutando It would be more than welcome.
I had some timing issues recently... but looking forward to getting back to the project asap. I've got some more knowledge with React and  started using more tools on daily basis and gonna give a second life to the boilerplate.... So all PR welcome! :)

**Comment by nicksp** [comment]
Hey @Lutando Do you think you'll have a chance to submit a PR for that?

**Comment by Lutando** [comment]
Hi @nicksp  I will definitely do that on Saturday how does that sound? :)

**Comment by Lutando** [comment]
Also would you like it done in the old style (routes defined in a routes.js folder as it is now) or the new composable style as per their docs. I guess either way is a matter of preference. I am tend to lean towards the latter option.

**Comment by nicksp** [comment]
That's great @Lutando, whenever you have a time. For sure i'd expect latest recommended composable style :)

**Comment by Lutando** [comment]
Almost done with it just need to cleanup some things, expect a PR in the next few days

**Comment by nicksp** [comment]
@Lutando Cool, really excited about that ;)

**Comment by circlingthesun** [comment]
This is great!
